trigger:
- master
- feature/sidebar

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '4f4b551b-8629-4658-8ba6-3a40bce1e953'
  webAppName: 'th-cl-ragpoc-webapp-rg1-JS'
  environmentName: 'th-cl-ragpoc-webapp-rg1-JS'
  vmImageName: 'ubuntu-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  imageRepository: 'yussaaa/th-chatbot' 
  imageTag: 'amd64' 

steps:
- checkout: self

# # Build the Docker image (optional if you're using a pre-built public image)
# - task: Docker@2
#   displayName: 'Build Docker Image'
#   inputs:
#     command: 'build'
#     repository: '$(imageRepository)'
#     dockerfile: 'WebApp.Dockerfile' # Only needed if you're building an image
#     tags: |
#       $(imageTag)

- task: AzureWebAppContainer@1
  displayName: 'Deploy Public Docker Image to Azure App Service'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(webAppName)'
    imageName: '$(imageRepository):$(imageTag)'